[package]
name = "rope"
version = "0.1.0"
authors = ["Ranadeep Biswas <ranadip.bswas@gmail.com>"]
edition = "2018"
description = "easy file transfer on same network"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
env_logger = "0.8.2"
log = "0.4.14"
rand = "0.8.3"
tokio = { version = "1.2.0", features = ["full"] }
tokio-stream = "0.1.3"
zenoh = "0.5.0-beta.7"
