[package]
name = "rope"
version = "0.2.0"
authors = ["Ranadeep Biswas <mail@rnbguy.at>"]
edition = "2021"
description = "easy file transfer on same network"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.59"
clap = { version = "3.2.16", features = ["derive", "cargo"] }
env_logger = "0.9.0"
if-addrs = "0.7.0"
indicatif = "0.17.0"
log = "0.4.17"
mdns-sd = "0.5.5"
names = { version = "0.14.0", default-features = false }
tokio = { version = "1.20.1", features = ["full", "rt-multi-thread", "net"] }
